import type { Metadata } from "next";
import "./globals.css";

const directionContract = `<!--
THESIS: The trip is an open working manual; uncertainty sits on the exact fact it qualifies, never in a distant disclaimer.
OWN-WORLD: Quiet paper field, ink rules, punched acetate verification layers, and full-strength section tabs; vermilion is reserved for unresolved warnings.
STORY: Describe the trip, inspect the open plan, understand cost and readiness, replace a choice, and confirm uncertain facts with suppliers.
FIRST VIEWPORT: Chat margin at left, active planning leaf in the center, stepped section tabs at right, and total/readiness across the top.
FORM: Tabbed reference manual; seed 896b79e7, selected challenger rw-manual-acetate-tab-board.
FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md
-->`;

function DirectionContractMarker() {
  return (
    <span
      hidden
      data-impeccable-direction-contract="896b79e7"
      dangerouslySetInnerHTML={{ __html: directionContract }}
    />
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <DirectionContractMarker />
        {children}
      </body>
    </html>
  );
}
